# .github/workflows/build.yml
# GitHub Actions configuration file for latex
# See https://github.com/xu-cheng/latex-action for details

name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    name: Generate pdf document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate pdf document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
          args: -file-line-error -halt-on-error -interaction=nonstopmode
          extra_fonts: |
            ./fonts/NotoSerifTC/*.otf
            ./fonts/Roboto/*.ttf
          pre_compile: tlmgr update --self && tlmgr update --all
          latexmk_shell_escape: true

      - name: Rename pdf document
        run: bash build_tools/github/rename.sh

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
             thesis_*.pdf
             figures/thesis-figure*.pdf
          if-no-files-found: error
